// <auto-generated />
using GarduinoWebAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace GarduinoWebAPI.Migrations
{
    [DbContext(typeof(MeasureContext))]
    partial class MeasureContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GarduinoWebAPI.Models.Measure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("AirHumidity");

                    b.Property<double>("AirTemperature");

                    b.Property<string>("SoilDescription")
                        .IsRequired();

                    b.Property<int>("SoilMoisture");

                    b.Property<Guid>("SourceId");

                    b.Property<DateTime>("Time");

                    b.HasKey("Id");

                    b.ToTable("Measure");
                });
#pragma warning restore 612, 618
        }
    }
}
